apiVersion: skaffold/v4beta9
kind: Config
build:
  artifacts:
  - image: skaffold-buildpacks
    buildpacks:
      env:
      - GOOGLE_RUNTIME_VERSION=8
    download:
      entry:
        - src: "."
          dst: "."
profiles:
- name: gcb
  build:
    googleCloudBuild: {}
