apiVersion: skaffold/v4beta9
kind: Config
build:
  artifacts:
  - image: skaffold-helm
    download:
      entry:
        - src: "."
          dst: "."
deploy:
  helm:
    releases:
    - name: skaffold-helm
      chartPath: charts
