# using default substitutions, provided by Google Cloud Build
# see: https://cloud.google.com/container-builder/docs/configuring-builds/substitute-variable-values#using_default_substitutions
steps:
# Build and tag skaffold-deps image using docker with cache-from
  - name: 'gcr.io/cloud-builders/docker'
    args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/build_deps:latest'
    - '--cache-from'
    - 'gcr.io/k8s-skaffold/build_deps:latest'
    - '-f'
    - 'deploy/skaffold/Dockerfile.deps'
    - '.'

# Build and tag skaffold builder
  - name: 'gcr.io/cloud-builders/docker'
    args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/skaffold-builder:latest'
    - '-f'
    - 'deploy/skaffold/Dockerfile'
    - '.'

  # Build and tag skaffold builder
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '--build-arg'
      - 'PROJECT_ID=$PROJECT_ID'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/eric-testing/skaffold:edge'
      - '-f'
      - 'deploy/skaffold/Dockerfile.binary'
      - '.'

# Check that skaffold is in the image
  - name: 'gcr.io/$PROJECT_ID/skaffold:edge'
    args:
    - 'skaffold'
    - 'version'

images:
- 'us-east1-docker.pkg.dev/$PROJECT_ID/eric-testing/skaffold:edge'

options:
  machineType: 'N1_HIGHCPU_8'

timeout: 1500s
