steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: /bin/bash
    args:
      - -c
      - |
        docker build -t us-east1-docker.pkg.dev/k8s-skaffold/scanning/skaffold:v1.37.3-lts --build-arg PROJECT_ID=$PROJECT_ID -f deploy/skaffold/Dockerfile.test .
images:
  - 'us-east1-docker.pkg.dev/k8s-skaffold/scanning/skaffold:v1.37.3-lts'