FROM alpine/curl as builder

RUN curl -Lo skaffold https://storage.googleapis.com/skaffold/v2.0.6/latest/skaffold-linux-amd64 && chmod +x skaffold

FROM gcr.io/distroless/static-debian11

COPY --from=builder skaffold /usr/bin/skaffold

