FROM alpine/curl as builder

RUN curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v1.37.3/skaffold-linux-amd64 && chmod +x skaffold

FROM gcr.io/distroless/static-debian11

COPY --from=builder skaffold /usr/bin/skaffold

