name: unit tests (linux)

# Triggers the workflow on push or pull request events
on: [push, pull_request]

permissions: read-all

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}-${{github.workflow}}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        path: "./"
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.17.0'
      - name: docker-image
        uses: "docker://ubuntu:22.04"
        with:
          entrypoint: bash
          args: "-c 'which go'"